CREATE DATABASE PROJECT;
USE PROJECT;

---ROLE TABLE---

CREATE TABLE ROLE (
ID INT, 
ROLE_NAME VARCHAR(100),
CONSTRAINT ROLE_ID_PK PRIMARY KEY(ID)
)
SELECT * FROM ROLE;


---USER_ACCOUNT TABLE---

CREATE TABLE USER_ACCOUNT (
ID INT,
USER_NAME VARCHAR(100),
EMAIL VARCHAR(254),
PASSWORD VARCHAR(200),
PASSWORD_SALT VARCHAR(50) NOT NULL,
PASSWORD_HASH_ALGORITHM VARCHAR(50),
CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY(ID)
)
SELECT * FROM USER_ACCOUNT;


---STATUS TABLE---

CREATE TABLE STATUS (
ID INT, 
STATUS_NAME VARCHAR(100),
IS_USER_WORKING BIT,
CONSTRAINT STATUS_ID_PK PRIMARY KEY(ID)
)
SELECT * FROM STATUS;


---USER HAS ROLE---

CREATE TABLE USER_HAS_ROLE (
ID INT,
ROLE_START_TIME DATETIME,
ROLE_END_TIME DATETIME NOT NULL,
USER_ACCOUNT_ID INT,
ROLE_ID INT,
CONSTRAINT USER_HAS_ROLE_ID_PK PRIMARY KEY (ID),
CONSTRAINT USER_HAS_ROLE_USER_ACCOUNT_ID FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
CONSTRAINT USER_HAS_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
)
SELECT * FROM USER_HAS_ROLE;


---USER HAS STATUS---

CREATE TABLE USER_HAS_STATUS (
ID INT,
STATUS_START_TIME DATETIME,
STATUS_END_TIME DATETIME NOT NULL,
USER_ACCOUNT_ID INT,
STATUS_ID INT,
CONSTRAINT USER_HAS_STATUS_ID_PK PRIMARY KEY (ID),
CONSTRAINT USER_HAS_STATUS_USER_ACCOUNT_ID FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
CONSTRAINT USER_HAS_STATUS_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID),
)
SELECT * FROM USER_HAS_STATUS;


---1.Insert data into each of the above tables. With at least two rows in each of 
-----the tables. Make sure that you have created respective foreign keys.

----ROLE TABLE

INSERT INTO ROLE VALUES(1,'USER1')
INSERT INTO ROLE VALUES(2,'USER2')

SELECT * FROM ROLE;

----USER_ACCOUNT TABLE

INSERT INTO USER_ACCOUNT VALUES(1,'ABC','ABC@XYZ.COM','ABC','ABCS','ABCPHA')
INSERT INTO USER_ACCOUNT VALUES(2,'DEF','DEF@XYZ.COM','DEF','DEFS','DEFPHA')

SELECT * FROM USER_ACCOUNT;

----STATUS TABLE

INSERT INTO STATUS VALUES(1,'NEW_STATUS',1)
INSERT INTO STATUS VALUES(2,'NEW_STATUS',1)

SELECT * FROM STATUS;

----USER_HAS_ROLE TABLE

INSERT INTO USER_HAS_ROLE VALUES(1,'1997-11-04 05:30:25',1,1,1)
INSERT INTO USER_HAS_ROLE VALUES(2,'1997-05-27 08:50:30',2,2,2)

SELECT * FROM USER_HAS_ROLE;

----USER_HAS_STATUS TABLE

INSERT INTO USER_HAS_STATUS VALUES(1,'2021-08-16 05:30:25',1,1,1)
INSERT INTO USER_HAS_STATUS VALUES(2,'2022-09-04 08:50:30',2,2,2)

SELECT * FROM USER_HAS_STATUS;


----2.Delete all the data from each of the tables.

---DELETING USER_HAS_STATUS

ALTER TABLE USER_HAS_STATUS DROP CONSTRAINT
USER_HAS_STATUS_ID_PK ,
USER_HAS_STATUS_USER_ACCOUNT_ID ,
USER_HAS_STATUS_STATUS_ID 

TRUNCATE TABLE USER_HAS_STATUS

SELECT * FROM USER_HAS_STATUS


---DELETING USER_HAS_ROLE

ALTER TABLE USER_HAS_ROLE DROP CONSTRAINT
USER_HAS_ROLE_ID_PK ,
USER_HAS_ROLE_USER_ACCOUNT_ID ,
USER_HAS_ROLE_ROLE_ID 

TRUNCATE TABLE USER_HAS_ROLE

SELECT * FROM USER_HAS_ROLE


---DELETING ROLE

ALTER TABLE ROLE DROP CONSTRAINT
ROLE_ID_PK 

TRUNCATE TABLE ROLE

SELECT * FROM ROLE


---DELETING USER_ACCOUNT

ALTER TABLE USER_ACCOUNT DROP CONSTRAINT
USER_ACCOUNT_PK 

TRUNCATE TABLE USER_ACCOUNT

SELECT * FROM USER_ACCOUNT


---DELETING STATUS

ALTER TABLE STATUS DROP CONSTRAINT
STATUS_ID_PK 

TRUNCATE TABLE STATUS

SELECT * FROM STATUS



